Repository coopnorge/mage-kubernetes-lib, pull requests merged in 2024-01, with the labels that each got.

#11 feat: Disable kubeconform schema skipping
  targets.go
  template.go
Labels: minor, enhancements

#12 feat: Add pallets validation
  pallets.go
  targets.go
  targets_test.go
  template.go
  utils.go
Labels: minor, enhancements

#14 feat: skip if no templates are provided
  targets.go
Labels: patch, minor, enhancements

#19 fix: Set server arg instead of SERVER_NAME
  argocd.go
  argocd_test.go
Labels: patch, bug-fix

#20 chore: Update GitHub's GPG key
  .policy.yml
Labels: patch, chore

#21 chore: Update from autoscaling/v2beta1 to autoscaling/v2
  tests/helm/fail/templates/hpa.yaml
  tests/helm/ok/templates/hpa.yaml
Labels: patch, chore

#23 fix: Allow legacy ".yml" extension for kustomize-file
  .gitignore
  argocd.go
  template.go
  utils.go
Labels: patch, release-drafter:patch, release-drafter:bug-fix
