Repository coopnorge/mage-kubernetes-lib, pull requests merged in 2024-11, with the labels that each got.

#44 Argo diff
  docker-compose/Dockerfile
  kyverno-policies/_helpers.tpl
  kyverno-policies/disallow-capabilities.yaml
  kyverno-policies/disallow-host-namespaces.yaml
  kyverno-policies/disallow-host-path.yaml
  kyverno-policies/disallow-host-ports.yaml
  kyverno-policies/disallow-host-process.yaml
  kyverno-policies/disallow-privileged-containers.yaml
  kyverno-policies/disallow-proc-mount.yaml
  kyverno-policies/disallow-selinux.yaml
  kyverno-policies/restrict-apparmor-profiles.yaml
  kyverno-policies/restrict-seccomp.yaml
  kyverno-policies/restrict-sysctls.yaml
  targets.go
  targets_test.go
  tests/templates/validate-fail/deployment-fail.yaml
  tests/templates/validate/deployment-ok.yaml
Labels: release-drafter-go:patch, release-drafter-go:minor

#50 feat: add kyverno validation as default target under validate
  targets.go
Labels: release-drafter:minor, release-drafter:enhancements, release-drafter-go:patch

#52 rewrite validate kyverno policies function to better handle rendered …
  targets.go
  targets_test.go
  tests/templates/validate-fail/deployment2-fail.yaml
  tests/templates/validate/deployment2-ok.yaml
Labels: release-drafter-go:patch
