Repository coopnorge/mage-kubernetes-lib, pull requests merged in 2024-10, with the labels that each got.

#40 fix: Go directive should use the full version
  go.mod
Labels: release-drafter:patch, release-drafter:bug-fix, release-drafter-go:patch

#39 fix: Exit with error if `argocd diff` exits with failure
  argocd.go
Labels: release-drafter:patch, release-drafter:bug-fix, release-drafter-go:patch

#42 chore: Remove auto approval workflow
  .github/workflows/approve-and-merge-dependabot-pr.yaml
Labels: release-drafter:patch, release-drafter:chore, release-drafter-go:patch

#47 feat: add pallet project to mage kubernetes lib
  .pallet/palletproject.yaml
Labels: release-drafter:minor, release-drafter:enhancements, release-drafter-go:patch

#48 disable pallet project for now
  .pallet/palletproject.yaml
Labels: release-drafter-go:patch
